substitutions:
  device: "esp_all_in_one"
  name: "all-in-one"
  friendly_name: "Svitlo Bot (AIO)"

esp32:
  variant: esp32c3
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://vantuzz/svitlobot/all-in-one/aio_esp32c3.yaml@trusted-aio

packages:
  - !include ../packages/common.yaml
  - !include ../packages/trusted_aio_svitlobot.yaml
  - !include ../packages/healthcheck.yaml
  - !include ../packages/custom_url.yaml
  - !include ../packages/sub_devices_all_in_one.yaml
  - !include ../packages/esp32.yaml
  - !include ../packages/trusted_aio_security.yaml
  - !include ../packages/trusted_aio_delivery.yaml
