substitutions:
  project_name: "ajs.Custom_URL"
  project_version: "3.5.57"

http_request:
  useragent: "esphome/${name} (${project_version})"
  verify_ssl: true
  timeout: 15s

globals:
  - id: custom_url_send_errors
    type: int
    restore_value: no
    initial_value: '-1'

web_server:
  version: 3
  sorting_groups:
    - id: custom_url_group
      name: "🤖 Custom URL"
      sorting_weight: -1

script:
  - id: !extend site_ping
    then:
      - logger.log: "Custom URL..."
      - script.execute: custom_url_ping
      - script.wait: custom_url_ping

  - id: custom_url_ping
    then:
      - script.execute: before_custom_url_ping
      - script.wait: before_custom_url_ping
      - if:
          condition:
            and:
              - wifi.connected:
              - lambda: 'return id(custom_url).has_state();'
              - lambda: 'return id(custom_url).state.find("http") != std::string::npos;'
              - lambda: |-
                  return true
                         ${"&& "~lets_ping if lets_ping is defined}
                         ${"&& "~i_am_master if i_am_master is defined};
          then:
            - script.execute: before_custom_url_request
            - script.wait: before_custom_url_request
            - http_request.get:
                url: !lambda |-
                  return id(custom_url).state;
                capture_response: false
                on_response:
                  then:
                    - lambda: id(custom_url_set_state)->execute(response->status_code, response->duration_ms);
                on_error:
                  then:
                    - script.execute:
                        id: custom_url_set_state
                        code: -1
                        duration: 0
            - component.update: custom_url_errors
            - script.execute: after_custom_url_request
            - script.wait: after_custom_url_request
          else:
            - script.execute: without_custom_url_request
            - script.wait: without_custom_url_request
      - script.execute: after_custom_url_ping
      - script.wait: after_custom_url_ping
    mode: single

  - id: custom_url_set_state
    parameters:
      code: int
      duration: int
    then:
      - script.execute: before_custom_url_state
      - script.wait: before_custom_url_state
      - lambda: |-
          if (code > 0) {
            id(custom_url_response_code).publish_state(std::to_string(code));
          } else {
            ESP_LOGE("Custom URL", "Request failed!");
            id(custom_url_response_code).publish_state("---");
          }

          if (duration > 0) {
            id(custom_url_response_duration).publish_state(duration);
          } else {
            id(custom_url_response_duration).publish_state(NAN);
          }

          if (code == 200) {
            ESP_LOGI("Custom URL", "Send status - success");
            id(custom_url_status).publish_state(true);
            id(custom_url_send_errors) = 0;
          } else {
            if (code > 0) {
              ESP_LOGE("Custom URL", "Send status - not success with response code: %d", code);
            }
            id(custom_url_status).publish_state(false);
            id(custom_url_send_errors) = id(custom_url_send_errors) < 0 ? 1 : std::max(1, ++id(custom_url_send_errors));
          }
      - script.execute: after_custom_url_state
      - script.wait: after_custom_url_state
    mode: single

  - id: before_custom_url_ping
    then:
      - logger.log: "Before ping..."

  - id: after_custom_url_ping
    then:
      - logger.log: "After ping..."

  - id: before_custom_url_request
    then:
      - logger.log: "Before request..."

  - id: after_custom_url_request
    then:
      - logger.log: "After request..."

  - id: without_custom_url_request
    then:
      - logger.log: "Without request..."

  - id: before_custom_url_state
    then:
      - logger.log: "Before state..."

  - id: after_custom_url_state
    then:
      - logger.log: "After state..."

text:
  - platform: template
    name: "Custom URL"
    id: custom_url
    optimistic: true
    mode: text
    restore_value: true
    icon: mdi:webhook
    entity_category: config
    disabled_by_default: true
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 5

binary_sensor:
  - platform: template
    name: "Status"
    id: custom_url_status
    icon: mdi:lan-connect
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 1

sensor:
  - platform: template
    name: "Delivery Errors"
    id: custom_url_errors
    lambda: |-
      if (!id(custom_url).has_state() || id(custom_url_send_errors) < 0) {
        return NAN;
      }
      return id(custom_url_send_errors);
    accuracy_decimals: 0
    icon: mdi:space-invaders
    unit_of_measurement: "error"
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 3
    on_value_range:
      - above: 10.0
        then:
          - button.press: Restart

  - platform: template
    name: "Response Duration"
    id: custom_url_response_duration
    icon: mdi:timer-outline
    entity_category: diagnostic
    disabled_by_default: true
    device_class: duration
    state_class: measurement
    unit_of_measurement: "ms"
    accuracy_decimals: 0
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 11

text_sensor:
  - platform: template
    name: "Response Code"
    id: custom_url_response_code
    icon: mdi:web
    entity_category: diagnostic
    disabled_by_default: true
    web_server:
      sorting_group_id: custom_url_group
      sorting_weight: 10
