substitutions:
  comment: "ESPHome Svitlo Bot | Shadow"

wifi:
  enable_btm: true
  enable_rrm: true

external_components:
  - source:
      type: git
      url: https://github.com/andrewjswan/esphome-components
      ref: 6b0202c47a5629358624271d062196b17ad3a340
    components: [shadow]
    refresh: 60s

shadow:
  id: svitlobot
  script_id: site_ping
  startup_delay: 5s
  interval: ${heartbeat_interval}s
  priority: 3

sensor:
  - platform: internal_temperature
    name: Device Temperature
    id: esp_temperature
    entity_category: diagnostic
    icon: mdi:coolant-temperature
    device_class: temperature
    disabled_by_default: true
