api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

web_server:
  auth:
    username: svitlobot
    password: !secret web_password

wifi:
  ap:
    password: !secret fallback_ap_password
